version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - public_network
    environment:
      - NGINX_HOST=netflix-frontend
    depends_on:
      - netflix-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Relative path

  netflix-frontend:
    image: lidorbashari/netflix-frontend:4
    container_name: netflix-frontend
    ports:
      - "3000:3000"
    networks:
      - public_network
      - private_network
    depends_on:
      - netflix-catalog
    environment:
      MOVIE_CATALOG_SERVICE: http://netflix-catalog:8080

  netflix-catalog:
    image: lidorbashari/netflix-movie-catalog:26
    container_name: netflix-catalog
    networks:
      - private_network
    volumes:
      - /mnt/ebs/persistent_data/catalog_data:/data  # EBS volume

    command: >
      sh -c "
        apt-get update &&
        apt-get install -y python3-pip &&
        pip3 install boto3 &&
        python3 /app/app.py
      "

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - private_network2
#    volumes:
#      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro  # Relative path
#      - /mnt/ebs/persistent_data/prometheus_data:/prometheus  # EBS volume
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"
    networks:
      - private_network2
    ports:
      - "3001:3000"
    volumes:
      - /mnt/ebs/persistent_data/grafana_data:/var/lib/grafana  # EBS volume
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro  # Relative path
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro  # Relative path
      - ./provisioning/dashboards/dashboards:/etc/grafana/provisioning/dashboards/dashboards:ro  # Relative path
    depends_on:
      - prometheus

  availability-agent:
    image: lidorbashari/availabilityagent:latest
    hostname: availability-agent
    container_name: availability-agent
    networks:
      - private_network2
      - public_network
    depends_on:
      - prometheus
    environment:
      MONITORED_HOST: http://netflix-frontend:3000

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
  private_network2:
    driver: bridge

#Volumes configuration (Now using absolute paths)
volumes:
  #We don't need volumes here because using absolute paths.
  #They are not being dynamically managed or created by Docker Compose.
  #If needed they will need to pre-exist on the machine in the specified location.
  catalog-data:
    driver_opts:
      type: none
      device: /mnt/ebs/catalog-data
      o: bind
  prometheus-data:
    driver_opts:
      type: none
      device: /mnt/ebs/prometheus-data
      o: bind
  grafana-data:
    driver_opts:
      type: none
      device: /mnt/ebs/grafana-data
      o: bind