global:
  scrape_interval: 15s  # How often to scrape targets by default.
  evaluation_interval: 15s  # How often to evaluate rules.

# A scrape configuration for monitoring Prometheus itself
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus's own metrics

  - job_name: 'availability-agent'
    static_configs:
      - targets: ['availability-agent:8081']  # Replace with the actual port used by your agent