apiVersion: v1
kind: Secret
metadata:
  name: yolo-credentials
type: Opaque
data:
  aws_access_key_id: {{ .Values.secrets.aws_access_key_id | b64enc | quote }}
  aws_secret_access_key: {{ .Values.secrets.aws_secret_access_key | b64enc | quote }}
