apiVersion: v1
kind: Secret
metadata:
  name: yolo-credentials
type: Opaque
stringData:
  aws_access_key_id: {{ .Values.secrets.aws_access_key_id | quote }}
  aws_secret_access_key: {{ .Values.secrets.aws_secret_access_key | quote }}