      
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.service.name }}

