apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.service.name }}
  ports:
    - port: {{ .Values.service.port }}
      name: mongo