name: tf apply for each state and region

on:
  workflow_dispatch:
    inputs:
      region:
        description: "choose region"
        required: true
        type: choice
        options:
          - eu-central-1.prod
          - us-east-1.dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: terraform fmt
        working-directory: tf/try
        run: terraform fmt -check
        continue-on-error: true

      - name: terraform init
        working-directory: tf/try
        run: |
          terraform init \
            -backend-config="bucket=lidor-netflix-infra-tfstate-try-2" \
            -backend-config="key=tfstate.json" \
            -backend-config="region=us-east-2"

      - name: terraform validate
        working-directory: tf/try
        run: terraform validate -no-color

      - name: Check local state
        working-directory: tf/try
        run: ls -la

      - name: terraform apply
        working-directory: tf/try
        run: terraform apply -auto-approve -var-file region.${{ github.event.inputs.region }}.tfvars
