apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend
  labels:
    app: netflix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
      labels:
        app: netflix-frontend
    spec:
      containers:
        - name: server
          image: lidorbashari/netflix-frontend:4
          env:
            - name: MOVIE_CATALOG_SERVICE
              value: "http://catalog-service:8080"
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: netflix-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: netflix-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001  # Optional field, if not specified, the control plane will allocate a port from a range (default: 30000-32767)